### ISSUE TITLE
Can we support LoL?

### ISSUE THREAD

**Issue by gislu** [AShujiao/vscode-maxPlus#2]
Strongly need that...

**Comment by AShujiao** [comment]
目前的游戏资讯都是max+这个app上获取的，这个app并没有lol的版块。
不过你可以提供下类似的lol资讯的app（我不玩lol所以不太清楚），我可以尝试抓包试下能不能集成上去。

**Comment by gislu** [comment]
Then I highly recommend do some plugin like zhihu, hupu & NGA
XD
